/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import {
  Day,
} from './models';

import {
  DayFate as DayFate
} from './components/day-fate/component';

declare global {
  interface HTMLDayFateElement extends DayFate, HTMLElement {
  }
  var HTMLDayFateElement: {
    prototype: HTMLDayFateElement;
    new (): HTMLDayFateElement;
  };
  interface HTMLElementTagNameMap {
    "day-fate": HTMLDayFateElement;
  }
  interface ElementTagNameMap {
    "day-fate": HTMLDayFateElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "day-fate": JSXElements.DayFateAttributes;
    }
  }
  namespace JSXElements {
    export interface DayFateAttributes extends HTMLAttributes {
      
        day?: Day,
        index?: number
    }
  }
}


import {
  DaySpinner as DaySpinner
} from './components/day-spinner/component';

declare global {
  interface HTMLDaySpinnerElement extends DaySpinner, HTMLElement {
  }
  var HTMLDaySpinnerElement: {
    prototype: HTMLDaySpinnerElement;
    new (): HTMLDaySpinnerElement;
  };
  interface HTMLElementTagNameMap {
    "day-spinner": HTMLDaySpinnerElement;
  }
  interface ElementTagNameMap {
    "day-spinner": HTMLDaySpinnerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "day-spinner": JSXElements.DaySpinnerAttributes;
    }
  }
  namespace JSXElements {
    export interface DaySpinnerAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  FateWheel as FateWheel
} from './components/fate-wheel/component';

declare global {
  interface HTMLFateWheelElement extends FateWheel, HTMLElement {
  }
  var HTMLFateWheelElement: {
    prototype: HTMLFateWheelElement;
    new (): HTMLFateWheelElement;
  };
  interface HTMLElementTagNameMap {
    "fate-wheel": HTMLFateWheelElement;
  }
  interface ElementTagNameMap {
    "fate-wheel": HTMLFateWheelElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fate-wheel": JSXElements.FateWheelAttributes;
    }
  }
  namespace JSXElements {
    export interface FateWheelAttributes extends HTMLAttributes {
      
    }
  }
}

